### ISSUE TITLE
Suggestion for U+041A CYRILLIC CAPITAL LETTER KA

### ISSUE THREAD

**Issue by VladWinner** [Derpitron/inter#5] opened 2022-01-14 12:35 UTC
Perhaps you can figure out how to roll back the changes to fix the shape of Cyrillic Capital ka (`К`)?
I posted my ideas here:
https://github.com/rsms/inter/issues/279#issuecomment-865121834

P.S. Thank you for implementing fixes!

**Comment by Derpitron** [comment] 2022-01-17 18:05
Hello, do you mean that you want the Cyrillic Capital Ka `К` to use the shape of the Latin Capital `K`?

**Comment by VladWinner** [comment] 2022-01-17 18:23
> the glyph is not being interpolated properly between the Thin and Regular weights
Since Inter v2.4, an error has been made in the coordinates in all styles for Capital `К` and Small `к`, and yes, in Thin→Regular it is most noticeable.

**Comment by Derpitron** [comment] 2022-01-17 18:54
Ah, I see. The Thin master (weight 100) and Black master (weight 900) seem to be symmetrical, so the issue is then only with the Regular master font (weight 400). 

Is this issue also present in the lower case?

Either way, it should be a simple fix. First i need to get my font to actually build, then I will try to fix the issue you've described.

**Comment by VladWinner** [comment] 2022-01-17 19:04
> Is this issue also present in the lower case?

Yes, but less noticeable. Here is a screenshot comparing Inter (left) with PT Root UI (right):
![image](https://user-images.githubusercontent.com/13555921/149825099-435ec48f-136d-4dc4-b323-137087814a29.png)

**Comment by Derpitron** [comment] 2022-01-18 04:03
Hi, I am beginning to edit the letter Kacyr. Does this look according to your expectations? (weight: 400)
**Upright**
![image](https://user-images.githubusercontent.com/46134462/149868908-f971cd69-de1d-4ddd-904c-abbd0503c3c5.png)
**Italic**
![image](https://user-images.githubusercontent.com/46134462/149868939-82019adc-d685-409b-a561-0bfcc18daedf.png)

**Comment by Derpitron** [comment] 2022-01-18 04:27
- [ ] Kadescendercyrillic U+049A
- [ ] Kahookcyrillic U+04C3
- [ ] Kabashkircyrillic U+04A0
- [ ] kabashkircyrillic U+04A1
- [ ] kadescendercyrillic U+049B
- [ ] kahookcyrillic U+04C4
- [ ] kaverticalstrokecyrillic U+049D
- [ ] kjecyrillic U+045C

**Comment by VladWinner** [comment] 2022-01-18 07:21
I tried to make changes to Kacyr in .glyphs (for Thin, Regular and Black weights), but unknowingly I couldn't get the exact coordinates (proportions are completely broken). But the approximate location of central dots is correct. I hope I can explain the difference with this.
Thin:
![image](https://user-images.githubusercontent.com/13555921/149889120-79fce7f9-9cc2-4840-bd25-caa35e4ffd53.png)
Regular:
![image](https://user-images.githubusercontent.com/13555921/149889177-2e4c7705-f567-49bd-bff6-a56b3702be21.png)
Black:
![image](https://user-images.githubusercontent.com/13555921/149889247-09114625-866d-4be3-a878-44bd2d2cf074.png)
[Inter.zip](https://github.com/Derpitron/inter/files/7886963/Inter.zip)

**Comment by Derpitron** [comment] 2022-01-18 07:34
Hello, I am so sorry for saying this, but I lost the saved file in a power outage. 

If it doesnt trouble you, could you make a list of the specific glyphs that need changing? Both for Inter Text and Inter Display?

**Comment by VladWinner** [comment] 2022-01-18 07:46
No problem. I would advise you to give up editing Inter Display in general, because the source file is unpolished and very broken compared to the usual Inter (Text).
Basic letters for Russian language are Kacyr `К` and kacyrillic `к`, the rest letters belong to other (Cyrillic-based) languages, and it would probably be better to postpone editing them and focus on these two glyphs.

**Comment by Derpitron** [comment] 2022-01-18 10:31
(offtopic) I have transcended my mortal limits. I am editing the positions of the nodes in the vector designs in a text editor now. None shall be able to stop my conquest of this universe, and all shall bow before me.
![image](https://user-images.githubusercontent.com/46134462/149920187-2a67c03f-9ca8-4496-a850-7c0249376a81.png)

**Comment by Derpitron** [comment] 2022-01-18 12:25
Hello! I've manually edited the Cyrillic glyphs for Kacyr and kacyrillic, for both Inter Text and Inter Display.

It was easier than I thought! I just had to search up the coordinates of the node within the plaintext editor (vscode) and manually edit it. This means that diff-merging should be much easier, and it will appear as if less lines have been changed. I am not closing this issue for now, as I would appreciate your input on my "designs".

**Comment by VladWinner** [comment] 2022-01-18 12:39
Okay, I'll need some time to see the result.

**Comment by Derpitron** [comment] 2022-01-18 12:43
Hello, the Inter fork on your profile does not seem to have any new commits at all. I edited the nodes myself. I tried to keep the new design similar in proportions to the original, so it might look different to your designs, noticeably in the "middle stem" region

**Comment by VladWinner** [comment] 2022-01-18 12:47
![image](https://user-images.githubusercontent.com/13555921/149939709-8e5e1f6e-ce54-48e4-a871-7652fdaa6634.png)
I added Inter.glyphs inside this archive in the post here, but as I said earlier, the proportions are not taken into account there and the width of the lines is distorted (so it was just like a concept, not a real solution).
I just checked your changes through FontLab and I can say that you have done a great job. I am glad that with the adoption of your commit, the issue will finally be fixed.

**Comment by Derpitron** [comment] 2022-01-18 12:52
Thank you :)) it means so much to me

**Closed** 2022-01-18 12:52 UTC

**Comment by Derpitron** [comment] 2022-01-18 12:55
By the way, do be careful when dealing with .glyphs files using FontLab. The FontLab .glyphs exporter doesn't output a correct file, and you won't be able to build the font properly using the fontlab exporter .glyphs file. I'm not sure why the exporter is broken, but it just is. I can't really find a solution to that issue so all I am doing right now is copying the changes made in the FontLab exported file (e.g new glyph, new design) and "grafting" it into the upstream .glyphs file which is known to work. 

this not only lets the font build properly, but it also lets you diff-compare the upstream .glyphs file with your own, and drastically cuts down on the "lines changed" during commits.
